[package]
name = "yuk"
version = "0.0.0"
edition = "2018"

[dependencies]
futures = { version = "0.3.1", features = ["thread-pool"] }
libc = { version = "0.2.66" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
